### PR TITLE
Cookbook: datetime recipe is missing a line of code

### PR DESCRIPTION
**Pull request by chrisxfire**
Add missing call to XAxis.DateTimeFormat

### CODE REVIEW

**Comment by chrisxfire** [comment]
I think there's a missing call in the documentation here, but haven't tested this yet.  Will wait until I can test it before I submit this PR.

**Comment by swharden** [comment]
Hi @chrisxfire, thanks for reporting this!

The broken cookbook recipe is here:
https://scottplot.net/cookbook/4.1/category/axis-and-ticks/#plotting-datetime-data

Note that the cookbook is generated automatically by this code:
https://github.com/ScottPlot/ScottPlot/blob/6c8bd0ca8bbabd623d5a53412f843d8715d552e5/src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs#L198-L223

It's amazing how such a small thing breaks stuff in such a big way, but I think the problem is here:
https://github.com/ScottPlot/ScottPlot/blob/6c8bd0ca8bbabd623d5a53412f843d8715d552e5/src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs#L223-L224

The cookbook is generated automatically by parsing the .cs files, and the fact that there's not a whitespace line above that class signature may be the core cause of this issue! If you create a PR over in the ScottPlot library that adds this line of whitespace, I can merge it in and update the cookbook on the website 🚀 

Thanks again for looking into this!

**Comment by swharden** [comment]
> haven't tested this yet. Will wait until I can test it before I submit this PR.

The core issue is described in https://github.com/ScottPlot/ScottPlot.NET/pull/25#issuecomment-1462235816 but I think this PR looks great and is a definite improvement! I'm going to merge it in now, and we can always refine it later with another PR if needed 👍

**Comment by chrisxfire** [comment]
@swharden peculiar!  Is that Hugo thing?  I've only built static sites with Jekyll but intend to give Hugo a shot this summer.

I'll open that PR as you recommend and we'll see if that does the trick.

**Comment by swharden** [comment]
> Is that Hugo thing?

It's a ScottPlot thing. I wrote a custom parser to read the .cs files and generate markdown for the Hugo website. My custom parser is finnicky I guess 😅 

> I'll open that PR as you recommend and we'll see if that does the trick

Awesome, thinks! If you make the code change and run the test suite, it should generate the cookbook on your local computer here:

```
src\ScottPlot4\ScottPlot.Cookbook\CookbookOutput\index.dev.html
```

You can check out if that code example is still missing the line that way

**Pull request merged**
