### PR TITLE
Created a new FAQ page index.md in ScottPlot.NET

### PR DESCRIPTION
**Pull request by anuragh2002**
Created a new FAQ page of index.md in ScottPlot.NET/content/faq/finance

Closes https://github.com/ScottPlot/ScottPlot/issues/2164

### CODE REVIEW

**Comment by swharden** [comment]
Hi @anuragh2002, thanks for this PR! It's not totally clear if it's complete or if you're still working on it. If it's done, let me know and I can make a few modifications and merge it shortly 👍

**Comment by anuragh2002** [comment]
Yeah @swharden I think it's done from my side. You can merge it!

**Comment by rosdyana** [comment]
I am so sorry @anuragh2002 , but that's just an empty page, where is the content? did you forget to add the detail mentioned here https://github.com/ScottPlot/ScottPlot/issues/2164#issue-1402382036 ?

**Comment by anuragh2002** [comment]
@rosdyana I was asked to create a FAQ page not write FAQs. I clarified that doubt, but @swharden asked me to just create an index.md page!

**Comment by swharden** [comment]
Hi @anuragh2002 and @rosdyana,

## This looks good / merging now / thanks!

@anuragh2002 thanks for this PR! I recognize my initial request was unclear. Indeed in my original comment I described that to create a new FAQ page you create an index.md and populate the header similar to the adjacent pages. https://github.com/ScottPlot/ScottPlot/issues/2164#issue-1402382036 This is what you did in this PR, and I will merge it tonight! Thanks for your contribution to this project! 👍🚀 

I'll copy some content over from the discussion into the file you started, then merge it tonight, and the webpage will be live.

## Miscommunication

@rosdyana is correct that what I _intended_ to communicate was that those are the steps to create a new page, but you can then populate it with content related to the solution discussed in [#2164](https://github.com/ScottPlot/ScottPlot/issues/2164).

The miscommunication is evidenced by the confusion I had in  https://github.com/ScottPlot/ScottPlot.NET/pull/15#issuecomment-1273793997 where I was uncertain whether this PR was complete or if you you were still working on it.

The topic came up in the Discord a couple days ago where I addressed the possibility of miscommunication: "in fairness I want to leave open the possibility that hyperliteral/miscommunication could be the result of a difference in native language"

No worries whatsoever! This stuff happens all the time, and I'm really happy that this community exist. It's amazing that strangers on the internet can collaborate anonymously to create fantastic software. Thanks to you and everyone who supports the open-source community!

**Pull request merged**
